--
-- PostgreSQL database dump
--

\restrict Qeti31slcIeaWuoXoyBSwohW3tGBTfpNTBgygjIUccqoAKJyY8jolbP2bUReZOM

-- Dumped from database version 16.15
-- Dumped by pg_dump version 16.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts (
    created_at timestamp(6) without time zone NOT NULL,
    credentials_version bigint NOT NULL,
    id bigint NOT NULL,
    phone character varying(16),
    password_hash character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    username character varying(254) NOT NULL,
    account_type character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT accounts_account_type_check CHECK (((account_type)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'EMPLOYEE'::character varying])::text[]))),
    CONSTRAINT accounts_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'LOCKED'::character varying])::text[])))
);


--
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attributes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attributes (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL
);


--
-- Name: attributes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attributes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attributes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    created_at timestamp(6) without time zone NOT NULL,
    employee_id bigint,
    id bigint NOT NULL,
    action character varying(255),
    details text,
    ip_address character varying(255),
    object_id character varying(255),
    object_type character varying(255),
    performed_by character varying(255)
);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: beauty_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.beauty_profiles (
    customer_id bigint,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    care_needs character varying(255),
    preferences character varying(255),
    price_range_interest character varying(255),
    skin_concerns character varying(255),
    skin_type character varying(255)
);


--
-- Name: beauty_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.beauty_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.beauty_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brands; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.brands (
    status smallint,
    id bigint NOT NULL,
    parent_id bigint,
    description character varying(255),
    name character varying(255),
    CONSTRAINT brands_status_check CHECK (((status >= 0) AND (status <= 1)))
);


--
-- Name: brands_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.brands ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brands_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart_items (
    quantity integer NOT NULL,
    cart_id bigint NOT NULL,
    id bigint NOT NULL,
    sku_id bigint NOT NULL
);


--
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.carts (
    customer_id bigint NOT NULL,
    id bigint NOT NULL
);


--
-- Name: carts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.carts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255),
    status character varying(255),
    CONSTRAINT categories_status_check CHECK (((status)::text = ANY ((ARRAY['INACTIVE'::character varying, 'ACTIVE'::character varying])::text[])))
);


--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_addresses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_addresses (
    is_default boolean,
    customer_id bigint,
    id bigint NOT NULL,
    address_detail character varying(255),
    district character varying(255),
    phone character varying(255),
    province character varying(255),
    recient_name character varying(255),
    ward character varying(255)
);


--
-- Name: customer_addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customers (
    dob date,
    join_date date,
    loyalty_points integer,
    account_id bigint,
    id bigint NOT NULL,
    full_name character varying(255),
    gender character varying(255),
    CONSTRAINT customers_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employee_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employee_roles (
    employee_id bigint NOT NULL,
    role_id bigint NOT NULL
);


--
-- Name: employee_stores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employee_stores (
    is_primary_branch boolean,
    employee_id bigint NOT NULL,
    store_id bigint NOT NULL
);


--
-- Name: employees; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employees (
    status smallint,
    account_id bigint NOT NULL,
    id bigint NOT NULL,
    full_name character varying(150) NOT NULL,
    internal_email character varying(255) NOT NULL,
    phone character varying(255),
    CONSTRAINT employees_status_check CHECK (((status >= 0) AND (status <= 1)))
);


--
-- Name: employees_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory (
    actual_stock integer NOT NULL,
    held_quantity integer NOT NULL,
    minimum_stock integer,
    id bigint NOT NULL,
    sku_id bigint NOT NULL,
    store_id bigint NOT NULL
);


--
-- Name: inventory_adjustments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_adjustments (
    quantity_after integer NOT NULL,
    quantity_before integer NOT NULL,
    id bigint NOT NULL,
    performed_at timestamp(6) without time zone NOT NULL,
    performed_by bigint,
    sku_id bigint NOT NULL,
    store_id bigint NOT NULL,
    reason character varying(255) NOT NULL
);


--
-- Name: inventory_adjustments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventory_adjustments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_adjustments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_items (
    quantity integer NOT NULL,
    snapshot_price numeric(18,2) NOT NULL,
    subtotal numeric(18,2) NOT NULL,
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    sku_id bigint NOT NULL,
    snapshot_product_name character varying(255) NOT NULL,
    snapshot_variant_name character varying(255)
);


--
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_stock_holds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_stock_holds (
    quantity integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    sku_id bigint NOT NULL,
    store_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT order_stock_holds_status_check CHECK (((status)::text = ANY ((ARRAY['HELD'::character varying, 'RELEASED'::character varying, 'COMMITTED'::character varying])::text[])))
);


--
-- Name: order_stock_holds_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_stock_holds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_stock_holds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    discount_amount numeric(18,2),
    shipping_fee numeric(18,2),
    subtotal numeric(18,2),
    total_amount numeric(18,2),
    cancelled_at timestamp(6) without time zone,
    completed_at timestamp(6) without time zone,
    confirmed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    customer_id bigint NOT NULL,
    id bigint NOT NULL,
    store_id bigint,
    voucher_id bigint,
    district character varying(255),
    note character varying(255),
    payment_method character varying(255),
    province character varying(255),
    recipient_name character varying(255),
    recipient_phone character varying(255),
    shipping_address character varying(255),
    status character varying(255) NOT NULL,
    ward character varying(255),
    CONSTRAINT orders_payment_method_check CHECK (((payment_method)::text = 'COD'::text)),
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING_CONFIRMATION'::character varying, 'CONFIRMED'::character varying, 'PREPARING'::character varying, 'SHIPPING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_tokens (
    account_id bigint NOT NULL,
    consumed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    token_hash character varying(64) NOT NULL
);


--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permissions (
    id bigint NOT NULL,
    code character varying(100) NOT NULL,
    name character varying(150) NOT NULL,
    description character varying(255)
);


--
-- Name: permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_images (
    is_primary boolean,
    sort_order integer,
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    image_url character varying(255) NOT NULL
);


--
-- Name: product_images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_skus; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_skus (
    price numeric(18,2) NOT NULL,
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    sku_code character varying(50) NOT NULL,
    shade character varying(255),
    status character varying(255),
    variant_name character varying(255),
    volume character varying(255),
    CONSTRAINT product_skus_status_check CHECK (((status)::text = ANY ((ARRAY['INACTIVE'::character varying, 'ACTIVE'::character varying])::text[])))
);


--
-- Name: product_skus_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_skus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_skus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    brand_id bigint,
    category_id bigint,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    description character varying(255),
    main_ingredients character varying(255),
    name character varying(255),
    origin character varying(255),
    status character varying(255),
    uses character varying(255),
    CONSTRAINT products_status_check CHECK (((status)::text = ANY ((ARRAY['INACTIVE'::character varying, 'ACTIVE'::character varying])::text[])))
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: purchase_order_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.purchase_order_items (
    quantity integer NOT NULL,
    subtotal numeric(18,2) NOT NULL,
    unit_price numeric(18,2) NOT NULL,
    id bigint NOT NULL,
    purchase_order_id bigint NOT NULL,
    sku_id bigint NOT NULL
);


--
-- Name: purchase_order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.purchase_order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: purchase_orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.purchase_orders (
    total_amount numeric(18,2),
    confirmed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    id bigint NOT NULL,
    receiving_store_id bigint NOT NULL,
    supplier_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT purchase_orders_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'CONFIRMED'::character varying])::text[])))
);


--
-- Name: purchase_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.purchase_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: return_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.return_items (
    quantity integer NOT NULL,
    id bigint NOT NULL,
    order_item_id bigint NOT NULL,
    return_request_id bigint NOT NULL,
    detail_reason character varying(255)
);


--
-- Name: return_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.return_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.return_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: return_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.return_requests (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    processed_at timestamp(6) without time zone,
    processed_by bigint,
    requested_at timestamp(6) without time zone NOT NULL,
    reason character varying(255),
    status character varying(255) NOT NULL,
    CONSTRAINT return_requests_status_check CHECK (((status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying])::text[])))
);


--
-- Name: return_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.return_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.return_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reviews (
    rating integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    customer_id bigint NOT NULL,
    id bigint NOT NULL,
    order_id bigint,
    product_id bigint NOT NULL,
    comment character varying(255),
    moderation_status character varying(255) NOT NULL,
    CONSTRAINT reviews_moderation_status_check CHECK (((moderation_status)::text = ANY ((ARRAY['VISIBLE'::character varying, 'HIDDEN'::character varying, 'PENDING'::character varying])::text[])))
);


--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role_permissions (
    permission_id bigint NOT NULL,
    role_id bigint NOT NULL
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(255)
);


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sku_attribute_values; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sku_attribute_values (
    attribute_id bigint NOT NULL,
    id bigint NOT NULL,
    sku_id bigint NOT NULL,
    value character varying(255) NOT NULL
);


--
-- Name: sku_attribute_values_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sku_attribute_values ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sku_attribute_values_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_transfer_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_transfer_items (
    quantity integer NOT NULL,
    id bigint NOT NULL,
    sku_id bigint NOT NULL,
    transfer_id bigint NOT NULL
);


--
-- Name: stock_transfer_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_transfer_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_transfer_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_transfers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_transfers (
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    destination_store_id bigint NOT NULL,
    id bigint NOT NULL,
    received_at timestamp(6) without time zone,
    shipped_at timestamp(6) without time zone,
    source_store_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT stock_transfers_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'IN_TRANSIT'::character varying, 'RECEIVED'::character varying])::text[])))
);


--
-- Name: stock_transfers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_transfers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_transfers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stores (
    latitude double precision,
    longitude double precision,
    id bigint NOT NULL,
    address character varying(255),
    name character varying(255) NOT NULL,
    operating_hours character varying(255),
    phone character varying(255),
    status character varying(255),
    CONSTRAINT stores_status_check CHECK (((status)::text = ANY ((ARRAY['INACTIVE'::character varying, 'ACTIVE'::character varying])::text[])))
);


--
-- Name: stores_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suppliers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.suppliers (
    id bigint NOT NULL,
    address character varying(255),
    email character varying(255),
    name character varying(255) NOT NULL,
    phone character varying(255),
    status character varying(255),
    CONSTRAINT suppliers_status_check CHECK (((status)::text = ANY ((ARRAY['INACTIVE'::character varying, 'ACTIVE'::character varying])::text[])))
);


--
-- Name: suppliers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.suppliers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suppliers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vouchers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vouchers (
    discount_value numeric(18,2) NOT NULL,
    max_discount numeric(18,2),
    min_order_value numeric(18,2),
    total_quantity integer,
    used_quantity integer,
    end_date timestamp(6) without time zone,
    id bigint NOT NULL,
    start_date timestamp(6) without time zone,
    code character varying(50) NOT NULL,
    discount_type character varying(255) NOT NULL,
    status character varying(255),
    CONSTRAINT vouchers_discount_type_check CHECK (((discount_type)::text = ANY ((ARRAY['PERCENT'::character varying, 'FIXED'::character varying, 'FREESHIP'::character varying])::text[]))),
    CONSTRAINT vouchers_status_check CHECK (((status)::text = ANY ((ARRAY['INACTIVE'::character varying, 'ACTIVE'::character varying])::text[])))
);


--
-- Name: vouchers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vouchers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vouchers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wishlist_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wishlist_items (
    added_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    wishlist_id bigint NOT NULL
);


--
-- Name: wishlist_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wishlist_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wishlist_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wishlists; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wishlists (
    customer_id bigint NOT NULL,
    id bigint NOT NULL
);


--
-- Name: wishlists_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wishlists ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wishlists_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts accounts_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_email_key UNIQUE (email);


--
-- Name: accounts accounts_phone_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_phone_key UNIQUE (phone);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: accounts accounts_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_username_key UNIQUE (username);


--
-- Name: attributes attributes_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attributes
    ADD CONSTRAINT attributes_name_key UNIQUE (name);


--
-- Name: attributes attributes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attributes
    ADD CONSTRAINT attributes_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: beauty_profiles beauty_profiles_customer_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.beauty_profiles
    ADD CONSTRAINT beauty_profiles_customer_id_key UNIQUE (customer_id);


--
-- Name: beauty_profiles beauty_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.beauty_profiles
    ADD CONSTRAINT beauty_profiles_pkey PRIMARY KEY (id);


--
-- Name: brands brands_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.brands
    ADD CONSTRAINT brands_pkey PRIMARY KEY (id);


--
-- Name: cart_items cart_items_cart_id_sku_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_cart_id_sku_id_key UNIQUE (cart_id, sku_id);


--
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- Name: carts carts_customer_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_customer_id_key UNIQUE (customer_id);


--
-- Name: carts carts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: customer_addresses customer_addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_addresses
    ADD CONSTRAINT customer_addresses_pkey PRIMARY KEY (id);


--
-- Name: customers customers_account_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_account_id_key UNIQUE (account_id);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- Name: employee_roles employee_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_roles
    ADD CONSTRAINT employee_roles_pkey PRIMARY KEY (employee_id, role_id);


--
-- Name: employee_stores employee_stores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_stores
    ADD CONSTRAINT employee_stores_pkey PRIMARY KEY (employee_id, store_id);


--
-- Name: employees employees_account_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_account_id_key UNIQUE (account_id);


--
-- Name: employees employees_internal_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_internal_email_key UNIQUE (internal_email);


--
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (id);


--
-- Name: inventory_adjustments inventory_adjustments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_adjustments
    ADD CONSTRAINT inventory_adjustments_pkey PRIMARY KEY (id);


--
-- Name: inventory inventory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT inventory_pkey PRIMARY KEY (id);


--
-- Name: inventory inventory_store_id_sku_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT inventory_store_id_sku_id_key UNIQUE (store_id, sku_id);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: order_stock_holds order_stock_holds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_stock_holds
    ADD CONSTRAINT order_stock_holds_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_token_hash_key UNIQUE (token_hash);


--
-- Name: permissions permissions_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_code_key UNIQUE (code);


--
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);


--
-- Name: product_images product_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT product_images_pkey PRIMARY KEY (id);


--
-- Name: product_skus product_skus_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_skus
    ADD CONSTRAINT product_skus_pkey PRIMARY KEY (id);


--
-- Name: product_skus product_skus_sku_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_skus
    ADD CONSTRAINT product_skus_sku_code_key UNIQUE (sku_code);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: purchase_order_items purchase_order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_order_items
    ADD CONSTRAINT purchase_order_items_pkey PRIMARY KEY (id);


--
-- Name: purchase_orders purchase_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT purchase_orders_pkey PRIMARY KEY (id);


--
-- Name: return_items return_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_items
    ADD CONSTRAINT return_items_pkey PRIMARY KEY (id);


--
-- Name: return_requests return_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT return_requests_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: role_permissions role_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (permission_id, role_id);


--
-- Name: roles roles_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_name_key UNIQUE (name);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: sku_attribute_values sku_attribute_values_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sku_attribute_values
    ADD CONSTRAINT sku_attribute_values_pkey PRIMARY KEY (id);


--
-- Name: stock_transfer_items stock_transfer_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_transfer_items
    ADD CONSTRAINT stock_transfer_items_pkey PRIMARY KEY (id);


--
-- Name: stock_transfers stock_transfers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_transfers
    ADD CONSTRAINT stock_transfers_pkey PRIMARY KEY (id);


--
-- Name: stores stores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stores
    ADD CONSTRAINT stores_pkey PRIMARY KEY (id);


--
-- Name: suppliers suppliers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT suppliers_pkey PRIMARY KEY (id);


--
-- Name: vouchers vouchers_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vouchers
    ADD CONSTRAINT vouchers_code_key UNIQUE (code);


--
-- Name: vouchers vouchers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vouchers
    ADD CONSTRAINT vouchers_pkey PRIMARY KEY (id);


--
-- Name: wishlist_items wishlist_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wishlist_items
    ADD CONSTRAINT wishlist_items_pkey PRIMARY KEY (id);


--
-- Name: wishlist_items wishlist_items_wishlist_id_product_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wishlist_items
    ADD CONSTRAINT wishlist_items_wishlist_id_product_id_key UNIQUE (wishlist_id, product_id);


--
-- Name: wishlists wishlists_customer_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wishlists
    ADD CONSTRAINT wishlists_customer_id_key UNIQUE (customer_id);


--
-- Name: wishlists wishlists_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wishlists
    ADD CONSTRAINT wishlists_pkey PRIMARY KEY (id);


--
-- Name: idx_reset_account; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reset_account ON public.password_reset_tokens USING btree (account_id);


--
-- Name: idx_reset_expiry; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reset_expiry ON public.password_reset_tokens USING btree (expires_at);


--
-- Name: order_stock_holds fk1x5up1rrvxc0m8ibqv0j5c53v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_stock_holds
    ADD CONSTRAINT fk1x5up1rrvxc0m8ibqv0j5c53v FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: inventory_adjustments fk29u9ejj2ro876659b4llww791; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_adjustments
    ADD CONSTRAINT fk29u9ejj2ro876659b4llww791 FOREIGN KEY (sku_id) REFERENCES public.product_skus(id);


--
-- Name: order_items fk2mbmbfy82tn7joyvldcdoim61; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fk2mbmbfy82tn7joyvldcdoim61 FOREIGN KEY (sku_id) REFERENCES public.product_skus(id);


--
-- Name: return_items fk2nfjf1atvp0qkpjvd517m6cq7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_items
    ADD CONSTRAINT fk2nfjf1atvp0qkpjvd517m6cq7 FOREIGN KEY (order_item_id) REFERENCES public.order_items(id);


--
-- Name: purchase_orders fk30e9d6kkjvgsj9c4ahwcprqvw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT fk30e9d6kkjvgsj9c4ahwcprqvw FOREIGN KEY (receiving_store_id) REFERENCES public.stores(id);


--
-- Name: employee_roles fk398vvu81xw154mvy3g2eytscn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_roles
    ADD CONSTRAINT fk398vvu81xw154mvy3g2eytscn FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: employee_roles fk3uwwaxeiucvfixgd45etkjgmg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_roles
    ADD CONSTRAINT fk3uwwaxeiucvfixgd45etkjgmg FOREIGN KEY (employee_id) REFERENCES public.employees(id);


--
-- Name: stock_transfers fk4ikw41lqetkycysljtpxu58nv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_transfers
    ADD CONSTRAINT fk4ikw41lqetkycysljtpxu58nv FOREIGN KEY (source_store_id) REFERENCES public.stores(id);


--
-- Name: reviews fk4sm0k8kw740iyuex3vwwv1etu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk4sm0k8kw740iyuex3vwwv1etu FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- Name: brands fk5kui0upkg80erkfju5en57qf7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.brands
    ADD CONSTRAINT fk5kui0upkg80erkfju5en57qf7 FOREIGN KEY (parent_id) REFERENCES public.brands(id);


--
-- Name: inventory fk5risd3b54r1toplhk8xgfib57; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT fk5risd3b54r1toplhk8xgfib57 FOREIGN KEY (store_id) REFERENCES public.stores(id);


--
-- Name: wishlists fk60mulb9dr06pbuur46ywfp8fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wishlists
    ADD CONSTRAINT fk60mulb9dr06pbuur46ywfp8fk FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- Name: sku_attribute_values fk64h0my6riavq8el31b5fx3rie; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sku_attribute_values
    ADD CONSTRAINT fk64h0my6riavq8el31b5fx3rie FOREIGN KEY (sku_id) REFERENCES public.product_skus(id);


--
-- Name: audit_logs fk6geiy0g1j2se38krkm52jvavh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT fk6geiy0g1j2se38krkm52jvavh FOREIGN KEY (employee_id) REFERENCES public.employees(id);


--
-- Name: carts fk8ba3sryid5k8a9kidpkvqipyt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT fk8ba3sryid5k8a9kidpkvqipyt FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- Name: employees fk8dwhb0qmor08fl06pde1bef3c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT fk8dwhb0qmor08fl06pde1bef3c FOREIGN KEY (account_id) REFERENCES public.accounts(id);


--
-- Name: return_items fk8v71eiqcifumrq8um2dw74kg6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_items
    ADD CONSTRAINT fk8v71eiqcifumrq8um2dw74kg6 FOREIGN KEY (return_request_id) REFERENCES public.return_requests(id);


--
-- Name: purchase_order_items fk93jnjc5aoa03mtm1dlvuixcpt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_order_items
    ADD CONSTRAINT fk93jnjc5aoa03mtm1dlvuixcpt FOREIGN KEY (sku_id) REFERENCES public.product_skus(id);


--
-- Name: inventory fk962amqk2b6x97xy5g86tfotrk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT fk962amqk2b6x97xy5g86tfotrk FOREIGN KEY (sku_id) REFERENCES public.product_skus(id);


--
-- Name: order_stock_holds fk99wgna4kkglf9cyuudm1u1db2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_stock_holds
    ADD CONSTRAINT fk99wgna4kkglf9cyuudm1u1db2 FOREIGN KEY (store_id) REFERENCES public.stores(id);


--
-- Name: products fka3a4mpsfdf4d2y6r8ra3sc8mv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fka3a4mpsfdf4d2y6r8ra3sc8mv FOREIGN KEY (brand_id) REFERENCES public.brands(id);


--
-- Name: password_reset_tokens fkakpd9ro0vywgwa7hqmpbdurma; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT fkakpd9ro0vywgwa7hqmpbdurma FOREIGN KEY (account_id) REFERENCES public.accounts(id);


--
-- Name: stock_transfers fkaphns6hqs1gw64babt1bpkdk4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_transfers
    ADD CONSTRAINT fkaphns6hqs1gw64babt1bpkdk4 FOREIGN KEY (created_by) REFERENCES public.employees(id);


--
-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: return_requests fkbski88d6kewx0cbj5pk7nes01; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT fkbski88d6kewx0cbj5pk7nes01 FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: orders fkdimvsocblb17f45ikjr6xn1wj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkdimvsocblb17f45ikjr6xn1wj FOREIGN KEY (voucher_id) REFERENCES public.vouchers(id);


--
-- Name: beauty_profiles fkef3e0hpqy3625jclukvc5j2w0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.beauty_profiles
    ADD CONSTRAINT fkef3e0hpqy3625jclukvc5j2w0 FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- Name: role_permissions fkegdk29eiy7mdtefy5c7eirr6e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fkegdk29eiy7mdtefy5c7eirr6e FOREIGN KEY (permission_id) REFERENCES public.permissions(id);


--
-- Name: stock_transfer_items fkertcckucd49nmw8ley2j5pxmh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_transfer_items
    ADD CONSTRAINT fkertcckucd49nmw8ley2j5pxmh FOREIGN KEY (transfer_id) REFERENCES public.stock_transfers(id);


--
-- Name: product_skus fkgfjst7dvihycy15ceiruv9roo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_skus
    ADD CONSTRAINT fkgfjst7dvihycy15ceiruv9roo FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: employee_stores fkglaf9vfnxbwqhgmy9q5tprprj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_stores
    ADD CONSTRAINT fkglaf9vfnxbwqhgmy9q5tprprj FOREIGN KEY (store_id) REFERENCES public.stores(id);


--
-- Name: employee_stores fkgy7ouhc6yletiu06rhkmsym9b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_stores
    ADD CONSTRAINT fkgy7ouhc6yletiu06rhkmsym9b FOREIGN KEY (employee_id) REFERENCES public.employees(id);


--
-- Name: cart_items fkia2f7yq196srm6ya3v96wafy6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fkia2f7yq196srm6ya3v96wafy6 FOREIGN KEY (sku_id) REFERENCES public.product_skus(id);


--
-- Name: stock_transfers fkjy28ixgk1qvc85yc60wva7xow; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_transfers
    ADD CONSTRAINT fkjy28ixgk1qvc85yc60wva7xow FOREIGN KEY (destination_store_id) REFERENCES public.stores(id);


--
-- Name: wishlist_items fkkem9l8vd14pk3cc4elnpl0n00; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wishlist_items
    ADD CONSTRAINT fkkem9l8vd14pk3cc4elnpl0n00 FOREIGN KEY (wishlist_id) REFERENCES public.wishlists(id);


--
-- Name: inventory_adjustments fkmc3wwbwwfeh380t5ysfe9ihhw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_adjustments
    ADD CONSTRAINT fkmc3wwbwwfeh380t5ysfe9ihhw FOREIGN KEY (performed_by) REFERENCES public.employees(id);


--
-- Name: return_requests fkmqeyw7laqcwfilu7hnpuokwg2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT fkmqeyw7laqcwfilu7hnpuokwg2 FOREIGN KEY (processed_by) REFERENCES public.employees(id);


--
-- Name: role_permissions fkn5fotdgk8d1xvo8nav9uv3muc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fkn5fotdgk8d1xvo8nav9uv3muc FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: sku_attribute_values fknqcn0533qeas1rcrs43gixg7y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sku_attribute_values
    ADD CONSTRAINT fknqcn0533qeas1rcrs43gixg7y FOREIGN KEY (attribute_id) REFERENCES public.attributes(id);


--
-- Name: orders fknqkwhwveegs6ne9ra90y1gq0e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fknqkwhwveegs6ne9ra90y1gq0e FOREIGN KEY (store_id) REFERENCES public.stores(id);


--
-- Name: purchase_order_items fko3yj8ocbw2kav38548t22hgh8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_order_items
    ADD CONSTRAINT fko3yj8ocbw2kav38548t22hgh8 FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id);


--
-- Name: products fkog2rp4qthbtt2lfyhfo32lsw9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: customers fkor0fx9fttvasr4grtaqnltyrl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT fkor0fx9fttvasr4grtaqnltyrl FOREIGN KEY (account_id) REFERENCES public.accounts(id);


--
-- Name: inventory_adjustments fkp9fd9bmfuowqk2urx1xf4rmjm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_adjustments
    ADD CONSTRAINT fkp9fd9bmfuowqk2urx1xf4rmjm FOREIGN KEY (store_id) REFERENCES public.stores(id);


--
-- Name: cart_items fkpcttvuq4mxppo8sxggjtn5i2c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES public.carts(id);


--
-- Name: reviews fkpl51cejpw4gy5swfar8br9ngi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkpl51cejpw4gy5swfar8br9ngi FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: order_stock_holds fkppgtam2m7pwyqy0dl3iy0nst; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_stock_holds
    ADD CONSTRAINT fkppgtam2m7pwyqy0dl3iy0nst FOREIGN KEY (sku_id) REFERENCES public.product_skus(id);


--
-- Name: purchase_orders fkpqy9fcrvmpk3ph36bnbp056xi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT fkpqy9fcrvmpk3ph36bnbp056xi FOREIGN KEY (created_by) REFERENCES public.employees(id);


--
-- Name: orders fkpxtb8awmi0dk6smoh2vp1litg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkpxtb8awmi0dk6smoh2vp1litg FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- Name: product_images fkqnq71xsohugpqwf3c9gxmsuy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT fkqnq71xsohugpqwf3c9gxmsuy FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: reviews fkqwgq1lxgahsxdspnwqfac6sv6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkqwgq1lxgahsxdspnwqfac6sv6 FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: wishlist_items fkqxj7lncd242b59fb78rqegyxj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wishlist_items
    ADD CONSTRAINT fkqxj7lncd242b59fb78rqegyxj FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: stock_transfer_items fkrbrbhlubhv3qtvux5ksb06op3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_transfer_items
    ADD CONSTRAINT fkrbrbhlubhv3qtvux5ksb06op3 FOREIGN KEY (sku_id) REFERENCES public.product_skus(id);


--
-- Name: purchase_orders fkrpdasmb8y8xs5tiy4369xpinq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT fkrpdasmb8y8xs5tiy4369xpinq FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id);


--
-- Name: customer_addresses fkrvr6wl9gll7u98cda18smugp4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_addresses
    ADD CONSTRAINT fkrvr6wl9gll7u98cda18smugp4 FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- PostgreSQL database dump complete
--

\unrestrict Qeti31slcIeaWuoXoyBSwohW3tGBTfpNTBgygjIUccqoAKJyY8jolbP2bUReZOM
