-- Manual versioned migration for the audited original schema; use psql ON_ERROR_STOP=1.
-- Review read-only inventory and back up first. No account is deleted or assigned a shared password.
BEGIN;
LOCK TABLE accounts, employees, customers IN ACCESS EXCLUSIVE MODE;
DO $$
BEGIN
 IF EXISTS (SELECT 1 FROM accounts WHERE email IS NULL OR trim(email)='' OR username IS NULL OR trim(username)='' OR password_hash IS NULL OR account_type IS NULL
   OR length(trim(email))>254 OR length(trim(username))>254 OR length(password_hash)>100) THEN
  RAISE EXCEPTION 'Identity preflight failed: missing/oversized identity. Reconcile affected accounts before migration.';
 END IF;
 IF EXISTS (SELECT 1 FROM accounts GROUP BY lower(trim(email)) HAVING count(*)>1)
 OR EXISTS (SELECT 1 FROM accounts GROUP BY lower(trim(username)) HAVING count(*)>1)
 OR EXISTS (SELECT 1 FROM accounts WHERE nullif(regexp_replace(trim(phone),'[[:space:]().-]','','g'),'') IS NOT NULL
            GROUP BY regexp_replace(trim(phone),'[[:space:]().-]','','g') HAVING count(*)>1) THEN
  RAISE EXCEPTION 'Identity preflight failed: duplicate normalized identifiers. Do not delete records automatically.';
 END IF;
 IF EXISTS (SELECT 1 FROM accounts WHERE nullif(trim(phone),'') IS NOT NULL
            AND regexp_replace(trim(phone),'[[:space:]().-]','','g') !~ '^\+?[0-9]{9,15}$') THEN
  RAISE EXCEPTION 'Identity preflight failed: invalid phone format.';
 END IF;
 IF EXISTS (SELECT 1 FROM employees WHERE account_id IS NULL OR full_name IS NULL OR trim(full_name)='' OR length(full_name)>150 OR internal_email IS NULL OR trim(internal_email)='')
 OR EXISTS (SELECT 1 FROM employees GROUP BY lower(trim(internal_email)) HAVING count(*)>1)
 OR EXISTS (SELECT 1 FROM employees GROUP BY account_id HAVING count(*)>1)
 OR EXISTS (SELECT 1 FROM employees e LEFT JOIN accounts a ON a.id=e.account_id WHERE a.id IS NULL OR a.account_type<>'EMPLOYEE')
 OR EXISTS (SELECT 1 FROM customers c LEFT JOIN accounts a ON a.id=c.account_id WHERE a.id IS NULL OR a.account_type<>'CUSTOMER') THEN
  RAISE EXCEPTION 'Employee/customer preflight failed: reconcile missing, duplicate or incorrect account links.';
 END IF;
END $$;
UPDATE accounts SET email=lower(trim(email)), username=lower(trim(username)),
 phone=nullif(regexp_replace(trim(phone),'[[:space:]().-]','','g'),'');
UPDATE employees SET internal_email=lower(trim(internal_email));
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS status varchar(255) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS credentials_version bigint NOT NULL DEFAULT 0;
ALTER TABLE accounts ALTER COLUMN email TYPE varchar(254), ALTER COLUMN email SET NOT NULL,
 ALTER COLUMN username TYPE varchar(254), ALTER COLUMN username SET NOT NULL,
 ALTER COLUMN password_hash TYPE varchar(100), ALTER COLUMN password_hash SET NOT NULL,
 ALTER COLUMN phone TYPE varchar(16), ALTER COLUMN account_type SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_accounts_email ON accounts(email);
CREATE UNIQUE INDEX IF NOT EXISTS uq_accounts_username ON accounts(username);
CREATE UNIQUE INDEX IF NOT EXISTS uq_accounts_phone ON accounts(phone);
ALTER TABLE employees ALTER COLUMN account_id SET NOT NULL, ALTER COLUMN full_name TYPE varchar(150),
 ALTER COLUMN full_name SET NOT NULL, ALTER COLUMN internal_email SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_employees_account ON employees(account_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_employees_internal_email ON employees(internal_email);
-- Preserve Employee ActiveStatus ORDINAL values and all legacy audit content.
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS employee_id bigint REFERENCES employees(id);
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS object_type varchar(255);
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS object_id varchar(255);
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS ip_address varchar(255);
ALTER TABLE audit_logs ALTER COLUMN details TYPE text;
CREATE TABLE IF NOT EXISTS password_reset_tokens (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 account_id bigint NOT NULL REFERENCES accounts(id),
 token_hash varchar(64) NOT NULL UNIQUE,
 created_at timestamp(6) with time zone NOT NULL,
 expires_at timestamp(6) with time zone NOT NULL,
 consumed_at timestamp(6) with time zone
);
CREATE INDEX IF NOT EXISTS idx_reset_account ON password_reset_tokens(account_id);
CREATE INDEX IF NOT EXISTS idx_reset_expiry ON password_reset_tokens(expires_at);
COMMIT;
